DELIMITER $$
CREATE PROCEDURE CONTRASEÑA_ACTUAL
(
    IDUSUARIO INT
)
BEGIN
	
    SELECT AES_DECRYPT(C.CONTRASEÑA, 'D3nvnC!@$*24/7*') FROM contraseñas C WHERE C.ID_TIPO = 1 AND C.ID_USUARIO = IDUSUARIO;
    
END $$;