DELIMITER $$
CREATE PROCEDURE ACTUALIZAR_CONTRASEÑA
(
	IDUSUARIO INT,
    CONTRASEÑA TEXT
)
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
    	ROLLBACK;
        SHOW ERRORS LIMIT 1;
    END;

	START TRANSACTION;
    
    DELETE FROM contraseñas WHERE ID_TIPO = 3 AND ID_USUARIO = IDUSUARIO;
    
	UPDATE contraseñas C SET C.ID_TIPO = 2
    WHERE C.ID_USUARIO = IDUSUARIO;
    
    INSERT INTO contraseñas VALUES (NULL, (AES_ENCRYPT(CONTRASEÑA, 'D3nvnC!@$*24/7*')), 1, IDUSUARIO);
    
    COMMIT;

END $$;