DELIMITER $$
CREATE PROCEDURE CREAR_DENUNCIA
(
    IDUSUARIO INT,
    TITULO TEXT,
    DESCRIPCION TEXT,
    FECHA DATETIME,
    ADJUNTE TEXT
)
BEGIN
	DECLARE IDDENUNCIA INT DEFAULT 0;
    DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
    	SHOW ERRORS LIMIT 1;
        ROLLBACK;
    END;
    
    START TRANSACTION;
    
    IF NOT EXISTS(SELECT * FROM denuncias D WHERE D.ID_USUARIO = IDUSUARIO AND D.TITULO = TITULO AND D.DESCRIPCION = D.DESCRIPCION AND D.FECHA_PUBLICACION = FECHA) THEN
    	INSERT INTO denuncias VALUES (NULL, NOW(), TITULO, DESCRIPCION, IDUSUARIO);
    	SET IDDENUNCIA = @@IDENTITY;
    ELSE
    	SET IDDENUNCIA = (SELECT D.ID_DENUNCIA FROM denuncias D WHERE D.ID_USUARIO = IDUSUARIO AND D.TITULO = TITULO AND D.DESCRIPCION = DESCRIPCION AND D.FECHA_PUBLICACION = FECHA);
    END IF;
    
    INSERT INTO adjuntes VALUES (NULL, ADJUNTE, IDDENUNCIA);
    
    COMMIT;
    
END $$;