DELIMITER $$
CREATE PROCEDURE ACTUALIZAR_DATOS
(
	IDUSUARIO INT,
    ANONIMO TEXT,
    CORREO TEXT,
    IDDEPTO INT
)
BEGIN

	DECLARE EXIT HANDLER FOR SQLEXCEPTION
    BEGIN
    	ROLLBACK;
        SHOW ERRORS LIMIT 1;
    END;

	START TRANSACTION;

	UPDATE usuario U SET U.ANONIMO = ANONIMO, U.CORREO = CORREO, U.ID_DEPTO = IDDEPTO
	WHERE U.ID_USUARIO = IDUSUARIO;
    
    COMMIT;

END $$;